TERRAN_COMMANDCENTER = 18
TERRAN_SCV = 45
TERRAN_SUPPLY_DEPOT = 19
TERRAN_BARRACKS = 21
TERRAN_BARRACKS_FLYING = 46
TERRAN_REFINERY = 20
NEUTRAL_MINERAL_FIELD = 341
NEUTRAL_VESPENE_MINE = 342
